server:
  port: 8081


spring:
  application:
    name: kafka-producer
    
  kafka:
    producer:
      bootstrap-servers: my-cluster.kafka.20.249.174.177.nip.io:32100
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        #partitioner.class: DefaultPartitioner <-- null
        #partitioner.class: org.apache.kafka.clients.producer.RoundRobinPartitioner
        #partitioner.class: org.apache.kafka.clients.producer.UniformStickyPartitioner
        #batch.size: 16384
        batch.size: 0
        #linger.ms: 10
    security:
      protocol: SASL_PLAINTEXT
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="edu-user" password="STlXElDAbVbntaoeiHv3Z7nPfgrSa1Dw";
        mechanism: SCRAM-SHA-512

topic:
  name: edu-topic03                 # 본인의 토픽명으로 수정할것
